---
datasources:
 - name: aws
   type: elasticsearch_aws
   host: search-foobar-es-pp5tqxzzceo6fwmo3lk2hhv5mq.eu-west-1.es.amazonaws.com
   region: eu-west-1
   index: foo
   get_boto_credentials: false
   access_key: AKIAJ4AAPKD5H5PW3YSA
   secret_key: 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

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077
