datasources:
  - name: influx
    type: influxdb
    addr: localhost
    database: dummy_db

  - name: elastic
    type: elasticsearch
    addr: localhost:9200
    index: dummy-idx

storage:
  path: /var/lib/loudml
