---
buckets:
  - name: influx
    type: influxdb
    addr: influxdb:8086
    database: telegraf
    measurement: loudml
  - name: kapacitor
    type: influxdb
    addr: kapacitor:9092
    database: from_loudml
    measurement: loudml

storage:
  path: /var/lib/loudml

server:
  listen: 0.0.0.0:8077
