version: 2
jobs:
  test-warp10:
    docker:
      - image: circleci/python:3.6.1
      - image: warp10io/warp10:2.0.3-ci
    environment:
      UNITTESTS: tests/test_warp10.py
      WARP10_URL: http://127.0.0.1:8080/api/v0
      WARP10_READ_TOKEN: readTokenCI
      WARP10_WRITE_TOKEN: writeTokenCI
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Wait for db
          command: dockerize -wait tcp://127.0.0.1:8080 -timeout 1m

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "base/vendor/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r base/vendor/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "base/vendor/requirements.txt" }}
      - run:
          name: Unit tests
          command: |
            . venv/bin/activate
            cd loudml
            unittests="$UNITTESTS" make unittest

  test-go:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/regel/loudml
    steps:
      - checkout

      - restore_cache:
          key: dep-0.5.0
      - run:
          name: 'Download Go dependencies tool'
          command: |
            cd /tmp
            wget -N https://github.com/golang/dep/releases/download/v0.5.0/dep-linux-amd64
            chmod +x /tmp/dep-linux-amd64
      - save_cache:
          name: 'dep-0.5.0'
          key: dep-0.5.0
          paths:
            - '/tmp/dep'

      - restore_cache:
          key: telemetry-vendor-{{ checksum "telemetry/Gopkg.lock" }}
      - run: 'cd telemetry && /tmp/dep-linux-amd64 ensure -v --vendor-only'
      - save_cache:
          name: 'telemetry vendored deps'
          key: telemetry-vendor-{{ checksum "telemetry/Gopkg.lock" }}
          paths:
            - 'telemetry/vendor'

      - run: 'cd telemetry && make test'

  test-python-unit:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "base/vendor/requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r base/vendor/requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "base/vendor/requirements.txt" }}
      - run:
          name: Unit tests
          command: |
            . venv/bin/activate
            cd loudml
            make unittest

workflows:
  version: 2
  check-warp:
    jobs:
      - test-warp10
  check:
    jobs:
      - test-go
      - test-python-unit
