---
datasources: []
# - name: influx
#   type: influxdb
#   addr: localhost
#   database: mydatabase
#   create_database: true
#   retention_policy: autogen
#   max_series_per_request: 2000

# - name: elastic
#   type: elasticsearch
#   addr: localhost:9200
#   index: myindex
#   doc_type: doc
#   max_series_per_request: 2000

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077

#inference:
#  num_cpus: 1
#  num_gpus: 0

#training:
#  num_cpus: 1
#  num_gpus: 0
#  incremental:
#    enable: True
#    crons:
#     - crontab: "0 2 * * *"
#       from: "now-1d"
#       to: "now"
#     - crontab: "0 3 1,8,15,22 * *"
#       from: "now-7d"
#       to: "now"

