---
datasources: []
# - name: influx
#   type: influxdb
#   addr: localhost
#   database: mydatabase
#   create_database: true
#   retention_policy: autogen

# - name: elastic
#   type: elasticsearch
#   addr: localhost:9200
#   index: myindex
#   doc_type: doc

storage:
  path: /var/lib/loudml

server:
  listen: localhost:8077
