# This is a Docker Compose file to work with LoudML and an InfluxDB stack.

version: "2"

services:
  loudml:
    image: loudml/community
    volumes:
      - ./etc/loudml.yml:/etc/loudml/config.yml:ro
      - ./var/loudml:/var/lib/loudml
    ports:
      - "8077:8077"
    depends_on:
      - influxdb

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - ./var/influxdb:/var/lib/influxdb

  chronograf:
    image: loudml/chronograf
    depends_on:
      - influxdb
      - loudml
    ports:
      - "8888:8888"
    environment:
      INFLUXDB_URL: http://influxdb:8086
      LOUDML_URL: http://loudml:8077
