# Site settings
title: "Loud ML Documentation"
email: contact@loudml.io
description: > # this means to ignore newlines until "baseurl:"
  The documentation site for Loud ML, the first open-source AI
  for ICT and IoT automation.

url: "http://localhost:4040" # the base hostname & protocol for your site
baseurl: "/docs" # the subpath of your site, e.g. /blog
gh_url: "https://github.com/regel/loudml"

plugins:
  - jekyll-assets
  - jekyll-sitemap

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - idseparator=_
    - source-highlighter=coderay
    - icons=font

